---


name: "dev image build and deployment"

on:

  push:
    branches:
      - dev


jobs:

   build:

     runs-on: ubuntu-latest
     env:
        packer_version: "1.9.4"

     steps:

       - name: "checkout repository"
         uses: actions/checkout@v3

       - name: "Packer installation"
         uses: hashicorp/setup-packer@main
         with:
           version: ${{ env.packer_version }}

       - name: "packer init"
         run: packer init .
         working-directory: ./packer/

       - name: "packer validate"
         run: packer validate -var-file="dev.pkvars.hcl" .
         working-directory: ./packer/

       - name: "format packer template"
         run: packer fmt .
         working-directory: ./packer/

       - name: "packer build image"
         run: packer build -var-file="dev.pkvars.hcl" .
         working-directory: ./packer/

       - name: "Notify Dev Deploy Job"
         uses: peter-evans/repository-dispatch@v2
         with:
           token: ${{ secrets.INFRA_PAT }}
           repository: pretabuu/myshop-web-infra
           event-type: deploy-infra
